language: cpp

compiler:
  - gcc

sudo: required
dist: trusty


before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh

script:
  - mkdir build && cd build
  - cmake ..
  - make

notifications:
  email: true